"""Per-expedition INSTRUCTIONS.md generation."""

from .catalog import glyphs_to_hex

TEMPLATE = """# {exp_name} — {version_label} ({difficulty})

Expedition generated by **Expedition Manager** from
[cwmonkey/nms-expeditions](https://cwmonkey.github.io/nms-expeditions/).

- **Version:** {version_label} (original release: {date_str})
- **Difficulty:** {difficulty}{difficulty_note}

## Expedition notes

{notice}

## Manual installation

1. Close No Man's Sky if it is running.
2. Copy `SEASON_DATA_CACHE_S22.JSON` (this file) to the game's cache folder,
   keeping the season name your game uses (`S22` for now; it is the same
   name as the `SEASON_DATA_CACHE_S*.json` file already in that folder):

   | Platform | Path |
   |---|---|
   | Steam PC | `%APPDATA%\\HelloGames\\NMS\\{{steam id}}\\cache` |
   | Steam Mac | `~/Library/Application Support/HelloGames/NMS/cache` |
   | MS Store / GOG / PC Game Pass | `%APPDATA%\\HelloGames\\NMS\\DefaultUser\\cache` |
   | Steam Deck | `/home/deck/.steam/steam/steamapps/compatdata/275850/pfx/drive_c/Users/SteamUser/AppData/Roaming/HelloGames/NMS/{{steam id}}/cache` |

   The file must keep the exact name shown above (match the case of the
   file the game already has in that folder, if any).
3. Start NMS **in offline mode** (Steam in offline mode) and begin the
   expedition from the Anomaly terminal.

## With Expedition Manager

```bash
# Install this expedition:
./run.sh install --exp {exp_id} --mode {mode} --difficulty {difficulty_flag}

# Uninstall (restores the original cache):
./run.sh uninstall
```

> **Note:** rewards you unlock stay on your account once you go back online.
"""

DIFFICULTY_NOTES = {
    "Defaults": " — original expedition parameters, unmodified.",
    "Easy": " — *Easy* preset applied (survival disabled, passive combat,\n  abundant resources, auto-fishing, etc.).",
    "Hardcore": " — *Hard Mode (Permadeath)* preset applied (full survival,\n  permadeath, harsh resources, full creature ecosystem, etc.).",
}


def render_instructions(exp, version, difficulty: str, glyph_map: dict) -> str:
    notices = []
    if exp.notice:
        notices.append(exp.notice)
    if version.notice:
        notices.append(version.notice)
    notice = "\n\n".join(notices) if notices else "_No specific notes._"
    notice = glyphs_to_hex(notice, glyph_map)

    return TEMPLATE.format(
        exp_name=exp.name.replace(":", " —"),
        version_label=version.label,
        difficulty=difficulty,
        difficulty_flag=difficulty.lower(),
        date_str=version.date_str,
        difficulty_note=DIFFICULTY_NOTES.get(difficulty, ""),
        notice=notice,
        exp_id=exp.id,
        mode="redux" if version.redux else "original",
    )
