"""Synchronization of the expedition library (downloads what is missing).

Reproduces the generator of the cwmonkey website: base + difficulty preset +
version patches (those with 'checked: 1') + global patches (those with
'checked: 1'), in that order, so the resulting files are byte-identical to
the ones produced by the website.
"""
import hashlib
import json
import re
from pathlib import Path

import yaml

from .catalog import build_catalog, build_glyph_map, build_prop_map
from .config import USER_OVERRIDES_FILE, load_config, migrate_user_data
from .instructions import render_instructions
from .merge import apply_overrides, build_overrides
from .sources import Sources

CACHE_FILE = "SEASON_DATA_CACHE_S22.JSON"
# Credit line identical to the one inserted by the website (credit to cwmonkey)
CREDIT_LINE = '"_generatedBy": "Generated by https://cwmonkey.github.io/nms-expeditions/ (Original files from BorisDeLeodium & /)",'


def _load_user_overrides() -> dict:
    """Read overrides.json: {"<exp_id>/<mode>/<difficulty>": {patch}, ...}.
    The patch uses the same language as the rest ([[removed]], [[append]], ...)."""
    migrate_user_data()  # one-time move from the program dir, if still there
    try:
        if USER_OVERRIDES_FILE.exists():
            data = json.loads(USER_OVERRIDES_FILE.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return data
    except (json.JSONDecodeError, OSError):
        pass
    return {}


def _strip_append_markers(text: str) -> str:
    """Strip residual '"[[append]]"' markers (same as the website)."""
    return re.sub(r'[ \t]*"\[\[append\]\]"(,?)\n', '', text)


def _global_patches(src) -> list:
    """Global patches (the ones the website applies by default to every exp)."""
    try:
        data = yaml.safe_load(src.fetch("_data/global_patches.yml")) or []
    except Exception:
        return []
    out = []
    for p in data:
        if p.get("checked") and p.get("json"):
            out.append(p)
    return out


def _patches_for(expedition, version) -> list:
    """Patches to apply to a version, in the EXACT order the website uses:
    exp.patches + version.patches (Liquid concatenation), only those with
    'checked: 1' that have a file."""
    combined = list(expedition.exp_patches or []) + list(version.patches or [])
    return [p for p in combined if p.get("checked") and p.get("json")]


def _as_js_numbers(obj):
    """In JS 1.0 == 1: integer-valued floats serialize as integers. Replicate that."""
    if isinstance(obj, dict):
        return {k: _as_js_numbers(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_as_js_numbers(v) for v in obj]
    if isinstance(obj, float) and obj.is_integer():
        # float.as_integer_ratio() yields the EXACT integer (repr only gives 17 digits)
        return obj.as_integer_ratio()[0]
    return obj


# ---------------- serialization identical to JS JSON.stringify ----------------

def _float_js_str(x: float) -> str:
    """Serialize a float exactly like JS Number.toString().

    JS uses decimal notation for 1e-6 <= |x| < 1e21 and exponential
    otherwise. Python's repr switches to exponential at 1e-4, hence this
    dedicated function.
    """
    if x != x or x in (float("inf"), float("-inf")):
        return "null"  # JSON.stringify(NaN/Infinity) === null
    r = repr(x)  # shortest representation (same digits as JS)
    if "e" in r or "E" in r:
        mant, exp = r.lower().split("e")
        e = int(exp)
        if 1e-6 <= abs(x) < 1e21:
            # rewrite in decimal notation (JS would not use exponential here)
            neg = mant.startswith("-")
            d = mant.lstrip("-").replace(".", "")  # significant digits
            # value = D * 10^(e - len(D) + 1); the point lands after (e+1) digits
            pos = e + 1
            if pos <= 0:
                s = "0." + "0" * (-pos) + d
            else:
                s = d[:pos] + ("." + d[pos:] if pos < len(d) else "")
            s = s.rstrip("0").rstrip(".")
            return ("-" if neg else "") + (s or "0")
        # JS-style exponential: d.ddd e±XX (no zero-padding of the exponent)
        sign = "-" if r.startswith("-") else ""
        m = r[1:] if sign else r
        dm, de = m.lower().split("e")
        dd = dm.replace(".", "")
        ee = int(de)
        mant_str = dd[0] + ("." + dd[1:] if len(dd) > 1 else "")
        esign = "e" + ("-" if ee < 0 else "+") + str(abs(ee))
        return f"{sign}{mant_str}{esign}"
    # plain decimal repr (|x| roughly between 1e-4 and 1e16): JS gives the same
    return r


_JSON_ESC = {"\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t",
             '"': '\\"', "\\": "\\\\"}


def _js_string(s: str) -> str:
    """JSON.stringify(s): JS escaping (characters >= 0x20 are left untouched)."""
    out = ['"']
    for ch in s:
        esc = _JSON_ESC.get(ch)
        if esc:
            out.append(esc)
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _to_js_text(obj, indent=0) -> str:
    """Equivalent to JS JSON.stringify(obj, null, 2)."""
    pad = "  " * indent
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        items = [f"{pad}  {_js_string(k)}: {_to_js_text(v, indent + 1)}" for k, v in obj.items()]
        return "{\n" + ",\n".join(items) + "\n" + pad + "}"
    if isinstance(obj, list):
        if not obj:
            return "[]"
        items = [f"{pad}  {_to_js_text(v, indent + 1)}" for v in obj]
        return "[\n" + ",\n".join(items) + "\n" + pad + "]"
    if isinstance(obj, bool):
        return "true" if obj else "false"
    if obj is None:
        return "null"
    if isinstance(obj, int):
        return str(obj)
    if isinstance(obj, float):
        return _float_js_str(obj)
    if isinstance(obj, str):
        return _js_string(obj)
    return str(obj)


def generate(base_text: str, version, difficulty: str, difficulty_overrides: dict,
             src, globals_: list, exp_patches: list = None,
             final_overrides: dict = None) -> str:
    """Generate the final JSON exactly as the cwmonkey website does,
    plus the user's personal adjustments (overrides.json) at the end.

    `difficulty_overrides` is the resolved preset for the selected difficulty
    (None for 'Defaults', the Easy/Hardcore preset overrides otherwise) — the
    website applies it through the exact same form/overrides mechanism.
    """
    merged = json.loads(base_text)
    if difficulty_overrides:
        merged = apply_overrides(merged, difficulty_overrides)
    for p in (exp_patches or []):
        merged = apply_overrides(merged, src.fetch_json(f"_includes/{p['json']}"))
    for p in globals_:
        merged = apply_overrides(merged, src.fetch_json(f"_includes/{p['json']}"))
    if final_overrides:
        merged = apply_overrides(merged, final_overrides)
    merged = _as_js_numbers(merged)
    text = _to_js_text(merged)
    return _strip_append_markers(_with_credit(text))


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _with_credit(text: str) -> str:
    """Insert the credit line after the opening brace (as the website does)."""
    idx = text.find("{")
    if idx == -1:
        return text
    return text[: idx + 1] + "\n  " + CREDIT_LINE + text[idx + 1:]


def _read_manifest(lib: Path) -> dict:
    """Read the library manifest.json (empty dict if absent/unreadable)."""
    manifest_path = lib / "manifest.json"
    try:
        if manifest_path.exists():
            return json.loads(manifest_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        pass
    return {}


def library_status(library_path: str = None) -> dict:
    """Download state of the library, for UI status badges.

    Returns {(exp_id, mode, difficulty): {"name", "sha256", "version_id"}}
    built from <LIB>/manifest.json. Empty dict if the library does not exist.
    """
    cfg = load_config()
    lib = Path(library_path or cfg["library_path"]).expanduser()
    return {(k.split("/")[0], k.split("/")[1], k.split("/")[2]): v
            for k, v in _read_manifest(lib).items() if isinstance(v, dict)}


def sync(force: bool = False, only_exp: str = None, library: str = None,
         progress=None) -> tuple:
    """Download/synchronize the library. Returns (downloaded, unchanged).

    `progress` is an optional callback progress(done, total, message) called
    once per (expedition × mode × difficulty) target processed; the CLI path
    passes None and the behaviour is unchanged.
    """
    cfg = load_config()
    lib = Path(library or cfg["library_path"]).expanduser()

    def _report(done, total, msg):
        if progress:
            progress(done, total, msg)

    print("Fetching expedition catalog...")
    src = Sources(Path(__file__).resolve().parent.parent / "data" / "sources",
                 force=force, log=(lambda m: progress(0, 0, m) if progress else None))
    catalog = build_catalog(src.fetch("_data/expeditions.yml"))
    prop_map = build_prop_map(src.fetch("_data/customizations.yml"))
    glyph_map = build_glyph_map(src.fetch("_data/glyphs.yml"))
    # Difficulty presets (website: presets.yml → customizations.*.json).
    # 'Defaults' means no preset; the rest map 1:1 to the website presets.
    easy_overrides = build_overrides(
        json.loads(src.fetch("_includes/customizations.easy_mode.json")), prop_map)
    hard_overrides = build_overrides(
        json.loads(src.fetch("_includes/customizations.hard_mode.json")), prop_map)
    presets_overrides = {"Easy": easy_overrides, "Hardcore": hard_overrides}
    globals_ = _global_patches(src)
    user_overrides = _load_user_overrides()

    manifest_path = lib / "manifest.json"
    manifest = _read_manifest(lib)

    downloaded = skipped = 0
    # Plan all targets first so the progress bar has a real total.
    targets = []
    for exp in catalog:
        if only_exp and exp.id != only_exp.lower():
            continue
        pairs = [("Originals", exp.original)]
        redux = exp.latest_redux
        if redux:
            pairs.append(("Redux", redux))
        for mode, version in pairs:
            for difficulty in ("Defaults", "Easy", "Hardcore"):
                targets.append((exp, mode, version, difficulty))

    total = len(targets)
    done = 0
    for exp, mode, version, difficulty in targets:
        done += 1
        _report(done, total, f"Processing {exp.id}/{mode}/{difficulty}")

        base_text = src.fetch(f"_includes/original/{version.json_file}")
        # generate() applies: difficulty preset (if any) + exp/version patches +
        # global patches (same order as the website) + overrides.json.
        content = generate(base_text, version, difficulty,
                           presets_overrides.get(difficulty), src, globals_,
                           exp_patches=_patches_for(exp, version),
                           final_overrides=user_overrides.get(f"{exp.id}/{mode}/{difficulty}"))

        sha = _sha256(content)
        key = f"{exp.id}/{mode}/{difficulty}"
        json_path = lib / mode / difficulty / exp.folder_name / CACHE_FILE

        if (not force and manifest.get(key, {}).get("sha256") == sha
                and json_path.exists()):
            skipped += 1
            continue

        folder = lib / mode / difficulty / exp.folder_name
        folder.mkdir(parents=True, exist_ok=True)
        json_path.write_text(content, encoding="utf-8")
        (folder / "INSTRUCTIONS.md").write_text(
            render_instructions(exp, version, difficulty, glyph_map),
            encoding="utf-8",
        )
        manifest[key] = {
            "exp_id": exp.id,
            "name": exp.name,
            "version_id": version.id,
            "mode": mode,
            "difficulty": difficulty,
            "sha256": sha,
        }
        downloaded += 1
        print(f"  ✓ {mode}/{difficulty}/{exp.folder_name}")

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return downloaded, skipped
